global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'url-shortener'
    static_configs:
      - targets: ['host.docker.internal:9090']  # ['localhost:9090']
    metrics_path: /metrics